#
# This is the config file used for the docker images.
# It allows all users to do anything, so don't use it on production systems.
#
# Do not configure host and port under `listen` in this file
# as it will be ignored when using docker.
# see https://github.com/verdaccio/verdaccio/blob/master/wiki/docker.md#docker-and-custom-port-configuration
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /verdaccio/storage

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
security:
  api:
    jwt:
      sign:
        expiresIn: 60d
        notBefore: 1
  web:
    sign:
      expiresIn: 7d

# a list of other known repositories we can talk to
uplinks:
  server2:
    url: http://verdaccio2:4873/

packages:
  '@jota/*':
    access: $all
    publish: $all
    proxy: server2
  '@*/*':
    access: $all
    publish: $all
    proxy: server2
  '**':
    access: $all
    publish: $all
    proxy: server2

middlewares:
  audit:
    enabled: true

logs:
  - { type: stdout, format: pretty, level: trace }
