services:
  verdaccio:
    image: verdaccio/verdaccio:nightly-master
    container_name: verdaccio-https
    ports:
      - '4873:4873'
    volumes:
      - './storage:/verdaccio/storage'
      - './conf:/verdaccio/conf'
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - verdaccio:verdaccio
    environment:
      DOMAINS: 'example.com -> http://verdaccio:4873'
      STAGE: local
      FORCE_RENEW: 'true'
