{{- if .Values.secrets.htpasswd }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "verdaccio.fullname" . }}-htpasswd
  labels:
    {{- include "verdaccio.labels" . | nindent 4 }}
stringData:
  htpasswd: |
    {{- range $user := .Values.secrets.htpasswd }}
    {{ htpasswd $user.username $user.password | toString }}
    {{- end }}
{{- end }}
