version: '2.1'
services:
  verdaccio:
    build: .
    container_name: verdaccio
    environment:
      - VERDACCIO_PORT
    ports:
      - $VERDACCIO_PORT:$VERDACCIO_PORT
    volumes:
       - verdaccio-storage:/verdaccio/storage
volumes:
  verdaccio:
    driver: local
