version: 2.1

aliases:
  - &repo_path
    ~/verdaccio
  - &defaults
    working_directory: *repo_path
  - &node_latest_browser_executor
    docker:
      - image: circleci/node:latest-browsers
  - &node_latest_executor
    docker:
    - image: circleci/node:latest
  - &node_lts_executor
    docker:
      - image: circleci/node:lts
  - &default_executor
    <<: *node_latest_executor
  - &yarn_cache_key
    yarn-sha-{{ checksum "yarn.lock" }}
  - &coverage_key
    coverage-{{ .Branch }}-{{ .Revision }}
  - &ignore_non_dev_branches
    filters:
      tags:
        only: /.*/
      branches:
        ignore:
          - gh-pages
          - l10n_master
          - /release\/.*/

commands:
  restore_repo:
    description: Restore repository from workspace
    steps:
      - attach_workspace:
          at: *repo_path
  run_test:
    description: Run test and functional test
    steps:
      - run:
          name: Test
          command: yarn run test
      - run:
          name: Functional test
          command: yarn test:functional

jobs:
  prepare:
    <<: *defaults
    <<: *default_executor
    steps:
      - checkout
      - restore_cache:
          key: *yarn_cache_key
      - run:
          name: Install dependencies
          command: yarn install --no-progress --pure-lockfile
      - run:
          name: Prepare CI
          command:  yarn run pre:ci
      - run:
          name: Build project
          command: yarn run code:build
      - save_cache:
          key: *yarn_cache_key
          paths:
            - ~/.yarn
            - ~/.cache/yarn
            - node_modules
      - persist_to_workspace:
          root: *repo_path
          paths:
            - ./*

  test_node_latest:
    <<: *defaults
    <<: *node_latest_executor
    steps:
      - restore_repo
      - run_test
      - save_cache:
          key: *coverage_key
          paths:
            - coverage

  test_node_lts:
    <<: *defaults
    <<: *node_lts_executor
    steps:
      - restore_repo
      - run_test

  test_e2e:
    <<: *defaults
    <<: *node_latest_browser_executor
    steps:
      - restore_repo
      - run:
          name: Test End-to-End
          command: yarn run test:e2e

  coverage:
    <<: *defaults
    <<: *default_executor
    steps:
      - restore_repo
      - restore_cache:
          key: *coverage_key
      - run:
          name: Publish coverage
          command: yarn run coverage:publish
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  workflow:
    jobs:
      - prepare:
          <<: *ignore_non_dev_branches
      - test_node_latest:
          requires:
            - prepare
          <<: *ignore_non_dev_branches
      - test_node_lts:
          requires:
            - prepare
          <<: *ignore_non_dev_branches
      - test_e2e:
          requires:
            - prepare
          <<: *ignore_non_dev_branches
      - coverage:
          requires:
            - test_node_latest
          <<: *ignore_non_dev_branches
