version: '3.1'

services:
  nginx:
    build:
      context: './nginx_ssl'
      dockerfile: Dockerfile
    ports:
      - '443:443'
      - '80:80'
    environment:
      - REMOTE_URL=http://verdaccio_relative_path_v5:4873/
    networks:
      - node-network
    container_name: 'nginx_ssl'
    depends_on:
      - verdaccio
      - verdaccio-root
  verdaccio:
    image: verdaccio/verdaccio:local
    container_name: 'verdaccio_relative_path_v5'
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - '4873:4873'
    volumes:
      - './storage:/verdaccio/storage'
      - './conf/v5:/verdaccio/conf'
  verdaccio-root:
    image: verdaccio/verdaccio:local
    container_name: 'verdaccio_relative_path_v5_root'
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=8000
    ports:
      - '8000:8000'
    volumes:
      - './storage:/verdaccio/storage'
      - './conf/v5_root:/verdaccio/conf'

networks:
  node-network:
    driver: bridge
