blank_issues_enabled: false
contact_links:
  - name: Question ğŸ¤·ğŸ»â€â™‚ï¸
    url: https://github.com/verdaccio/verdaccio/discussions/new
    about: ğŸ†• Open a new discussion and select category **Q&A** ğŸ™
  - name: Security Report ğŸ›¡
    url: https://github.com/verdaccio/verdaccio/security/policy
    about: I want to report a security vulnerability
  - name: Chat ğŸ˜
    url: http://chat.verdaccio.org
    about: For a quick question you should do it through our community chat
  - name: User Interface Report ğŸ‘©ğŸ¼â€ğŸ¨ğŸ‘¨ğŸ¼â€ğŸ¨
    url: https://github.com/verdaccio/ui/issues/new/choose
    about: Any report related with the User Interface should be posted in another repository
