blank_issues_enabled: false
contact_links:
  - name: Documentation ğŸ“š
    url: https://verdaccio.org/docs/en/installation
    about: Find more information in our documentation resources
  - name: Feature Request ğŸŒŸ
    url: https://github.com/orgs/verdaccio/discussions/new?category=ideas
    about: ğŸ†• Open a new feature request discussion ğŸ™
  - name: Question ğŸ¤·ğŸ»â€â™‚ï¸
    url: https://github.com/verdaccio/verdaccio/discussions/new?category=q-a
    about: ğŸ†• Open a new Q&A discussion ğŸ™
  - name: Chat ğŸ˜
    url: https://discord.gg/7qWJxBf
    about: Quick question? Try out Discord chat, you can get faster feedback
