blank_issues_enabled: true
contact_links:
  - name: Question ğŸ¤·ğŸ»â€â™‚ï¸
    url: https://github.com/verdaccio/verdaccio/discussions/new?category=q-a
    about: ğŸ†• Open a new Q&A discussion ğŸ™
  - name: Security Report ğŸ›¡
    url: https://github.com/verdaccio/verdaccio/security/policy
    about: I want to report a security vulnerability (note no bug bounty program available)
  - name: Chat ğŸ˜
    url: https://discord.gg/7qWJxBf
    about: Quick question? Try out Discord chat, you can get faster feedback
