version: '2'

services:
  verdaccio:
    image: verdaccio/verdaccio:local
    container_name: verdaccio_root_path
    ports:
      - '4873:4873'
    volumes:
      - verdaccio:/verdaccio

  nginx:
    restart: always
    build: conf/nginx
    ports:
      - '80:80'
    volumes:
      - /www/public
    volumes_from:
      - verdaccio
    links:
      - verdaccio:verdaccio

volumes:
  verdaccio:
    driver: local
