name: Changesets Publish Test

on:
  pull_request:

concurrency:
  group: changeset-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version:
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install dependencies with a custom registry
        uses: ./.github/actions/install-app
      - name: crowdin download
        env:
          CROWDIN_VERDACCIO_API_KEY: ${{ secrets.CROWDIN_VERDACCIO_API_KEY }}
          CONTEXT: production
        run: pnpm crowdin:download
      - name: build
        run: pnpm build
      - name: Docker test
        run: |
          docker run -d -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio:6
      - name: login
        run: npx npm-cli-login -u test -p 1234 -e test@domain.test -r http://localhost:4873
      - name: Prepare
        # to allow local snapshot
        run: rm .changeset/pre.json
      - name: Create snapshot
        run: pnpm local:snapshots
      - name: Changeset version
        run: pnpm local:publish
