name: E2E Docker Proxy Apache Test

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  schedule:
    # run every sunday
    - cron: '0 0 * * 0'
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
      
    - name: Start containers
      run: docker-compose -f "./e2e/docker/apache-verdaccio/docker-compose.yaml" up -d --build

    - name: Install node
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
      with:
        node-version: 18
    - name: verdaccio cli
      run: npm install -g verdaccio --registry http://localhost
    - name: gastby cli 
      run:  npm install -g gatsby-cli --registry http://localhost
    - name: netlify cli 
      run:  npm install -g netlify-cli --registry http://localhost
    - name: angular cli 
      run:  npm install -g @angular/cli --registry http://localhost

    - name: Stop containers
      if: always()
      run: docker-compose -f "./e2e/docker/apache-verdaccio/docker-compose.yaml" down
