on: [push, pull_request]
#on:
#  schedule:
#  - cron: '0 */4 * * *'
#  push:
#    paths-ignore:
#    - 'wiki/**'
#    - 'assets/**'
#    - 'docs/**'
#    - 'systemd/**'
#    - 'contrib/**'
#  pull_request:
#    branches:
#    - '**'

name: 'E2E Gatsby.js CLI with verdaccio'
jobs:
  npm:
    name: 'npm:gatsby example'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: 'Use Node.js 10.x'
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: 'install latest npm'
        run: npm i -g npm
      - name: Install Dependencies
        run: yarn install --pure-lockfile
      - name: 'Run verdaccio in the background'
        run: |
          nohup node ./scripts/run-verdaccio.js &
      - name: 'Ping to verdaccio'
        run: |
          npm ping --registry http://localhost:4873
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          echo "registry=http://localhost:4873" > ~/.npmrc
          npm config set loglevel="http"
          npm config set fetch-retries="5"
          npm config set fetch-retry-factor="50"
          npm config set fetch-retry-mintimeout="20000"
          npm config set fetch-retry-maxtimeout="80000"
          cat ~/.npmrc
          npm i -g gatsby
          gatsby new my-gatsby --verbose
          cd my-gatsby
          npm run build
