name: Release

on:
  push:
    tags:
      - '*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Use Node (latest)
      uses: actions/setup-node@v2.5.1
      with:
        node-version: 14
    - name: Install
      run: yarn install
    - name: Build
      run: yarn code:build
    - name: Publish
      run: sh scripts/publish.sh
      env:
        REGISTRY_AUTH_TOKEN: ${{ secrets.REGISTRY_AUTH_TOKEN }}
        REGISTRY_URL: registry.npmjs.org
    # FIXME: there is an issue where all the changelog is copied to the release notes (all versions)
    # - name: Create release notes
    #   run: sh scripts/github-release.sh
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
