name: Release Canary 5.x

on:
  workflow_dispatch:
  push:
    branches:
      - 5.x
      - 'jota/**'
      - 'canary/**'
      - '5x-refactor-test'
jobs:
  release:
    name: Release Snapshot
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - name: Use Node (latest)
      uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
      with:
        node-version-file: '.nvmrc'
    - name: Install
      run: yarn install
    - name: Build
      run: yarn build
    - name: Bump up package
      run: npm version prerelease --no-git-tag-version --preid $(date +%s%N)      
    - name: Publish
      run: sh scripts/publish-prerelease.sh
      env:
        REGISTRY_AUTH_TOKEN: ${{ secrets.VERDACCIO_REGISTRY_TOKEN_CANARY }}
        REGISTRY_URL: registry.verdaccio.org
