name: Module Smoke Test

on: [push, pull_request]  

permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}-6x
  cancel-in-progress: true    
jobs:
  test:    
    strategy:
      fail-fast: false
      matrix:
        node_version: [18, 20, 21, 22]    
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2    
      - name: Use Node ${{ matrix.node_version }}
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ matrix.node_version }}
      - name: Docker test
        run: |
            docker run -d -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio:5
      - name: login    
        run: npx npm-cli-login -u test -p 1234 -e test@domain.test -r http://localhost:4873                 
      - name: Build
        run: yarn && yarn build
      - name: Types
        run: yarn code:types           
      - name: Bump up package
        run: npm version prerelease --no-git-tag-version --preid $(date +%s%N)          
      - name: publish verdaccio 
        run:  npm publish --registry http://localhost:4873
      - name: install verdaccio 
        run:  npm i -g verdaccio --loglevel info --registry http://localhost:4873
      - name: verdaccio version 
        run:  verdaccio --version
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          npm init --force
          npm install jest@27.5.1 --registry http://localhost:4873
          npm install verdaccio --registry http://localhost:4873
          echo "test('require module should works', () => { const {runServer} = require('verdaccio') });" | tee module.spec.js
          cat module.spec.js
          yarn jest    
