name: Module Smoke Test 5.x
on:
  workflow_dispatch:
  push:
    # branches:
    #   - 5.x
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version: 18
      - name: Docker test
        run: |
            docker run -d -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio:5.x-next
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
      - name: 'Use Node.js 18.x'
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # tag=v2.5.1
        with:
          node-version: 18.x     
      - name: login    
        run: npx npm-cli-login -u test -p 1234 -e test@domain.test -r http://localhost:4873                 
      - name: Bump up package
        run: npm version prerelease --no-git-tag-version --preid $(date +%s%N)          
      - name: publish verdaccio 
        run:  npm publish --registry http://localhost:4873
      - name: install verdaccio 
        run:  npm i -g verdaccio --loglevel verbose --registry http://localhost:4873
      - name: jest 
        run:  npm i -g jest --registry http://localhost:4873
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          npm init --force
          npm install verdaccio --registry http://localhost:4873
          echo "it('should pass', () => { const {runServer} = require('verdaccio') });" | tee pass.test.js
          yarn jest pass.test.js          
