---
name: static data

on:
  workflow_dispatch:
  schedule:
    # twice peer week
    - cron: '0 0 * * 1,4'
  # for now, scheduled, we can enable on push master but not make much sense now
  # push:
  #   branches:
  #     - master

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  prepare:
    name: Run script
    runs-on: ubuntu-latest
    if: github.repository == 'verdaccio/verdaccio'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 18.x
      - name: install pnpm
        run: sudo npm i pnpm@latest-8 -g
      - name: install dependencies
        run: pnpm install
      - name: Build Translations percentage
        run: pnpm --filter @verdaccio/crowdin-translations build
      - name: update contributors
        run: pnpm run contributors
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: update addson data
        run: pnpm script:addson
      - name: update translations
        run: pnpm run translations
        env:
          TOKEN: ${{ secrets.CROWDIN_VERDACCIO_API_KEY }}          
      - name: format
        run: pnpm format
      - name: Commit & Push changes
        uses: actions-js/push@5a7cbd780d82c0c937b5977586e641b2fd94acc5 # tag=v1.5
        with:
          github_token: ${{ secrets.TOKEN_VERDACCIOBOT_GITHUB }}
          message: "chore: updated static data"
          branch: master
          author_email: verdaccio.npm@gmail.com
          author_name: verdacciobot
