name: UI Components

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' 

permissions:
  contents: read  #  to fetch code (actions/checkout)

env:
  DEBUG: verdaccio*

jobs:
  deploy:
    permissions:
      contents: read  #  to fetch code (actions/checkout)
      deployments: write
      pull-requests: write  #  to comment on pull-requests

    runs-on: ubuntu-latest
    if: github.repository == 'verdaccio/verdaccio'
    env:
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Use Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v3
        with:
          node-version-file: '.nvmrc'

      - name: Cache pnpm modules
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v3
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

      - name: Install pnpm
        run: |
          corepack enable
            corepack prepare --activate pnpm@8.9.0
      - name: Install
        run: pnpm install  
      - name: Build storybook
        run: pnpm ui:storybook:build
      - name: Copy public content
        # the msw.js worker is need it at the storybook-static folder in production
        run: cp -R packages/ui-components/public/* packages/ui-components/storybook-static
      - name: Deploy to Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_UI_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: pnpm --filter ...@verdaccio/ui-components netlify:ui:deploy
