on:
  workflow_call:
    inputs:
      docker_tag:
        required: true
        type: string
        description: 'Docker tag to use for the verdaccio image'
        default: '5'  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Use Node (latest)
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
      - name: Docker test
        run: |
            docker run -d -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio:${{ inputs.docker_tag }}
      - name: login    
        run: npx npm-cli-login -u test -p 1234 -e test@domain.test -r http://localhost:4873                 
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Types
        run: yarn code:types
      - name: Bump up package
        run: npm version prerelease --no-git-tag-version --preid $(date +%s%N)
      - name: publish verdaccio 
        run:  npm publish --registry http://localhost:4873
      - name: install verdaccio 
        run:  npm i -g verdaccio --loglevel info --registry http://localhost:4873
      - name: verdaccio version 
        run:  verdaccio --version
      - name: 'Running the integration test'
        run: |
          source scripts/e2e-setup-ci.sh
          npm init --force
          npm install jest --registry http://localhost:4873
          npm install verdaccio --registry http://localhost:4873
          echo "test('require module should works', () => { const {runServer} = require('verdaccio') });" | tee module.spec.js
          cat module.spec.js
          yarn jest    
